name: WheelOfDeath
version: 1.0.0
main: dev.digitaldragon.WheelOfDeath.WheelOfDeath
description: Wheel of Death
author: DigitalDragon
website: https://digitaldragon.dev
api-version: '1.20'
softdepend:
  - FastAsyncWorldEdit
